image: comp1720/site-gitlab-ci:0.6.5

variables:
  SCHEMA_BASE_URL: https://comp.anu.edu.au/courses/comp1720/assets/schemas
  DEST_DIR: /srv/gitlab-ce-pages/public/main/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/
  COMP1720_TEST_URL: https://comp1720.cecs.anu.edu.au/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/

generate_jobs:
  image: comp1720/gitlab-ci:0.0.8
  tags:
    - comp1720
  stage: build
  script:
    - python3 /jobs.py generate-ci .file-check-ci.yml . comp1720/gitlab-ci:0.0.8 -WC 89 -N file_check
  artifacts:
    paths:
      - .file-check-ci.yml

file_check:
  stage: test
  needs: ["generate_jobs"]
  allow_failure: true
  trigger:
    strategy: depend
    include:
      - artifact: .file-check-ci.yml
        job: generate_jobs

artist-statement-wordcount:
  image: ubuntu:20.04
  stage: test
  allow_failure: true
  tags:
    - comp1720
  script:
    - echo "Word Count:"
    - var="$(cat artist-statement.md | wc -w)"
    - > 
      if (( $var < 100)); then
        echo "Your artist statement should be more than 100 words!";
        exit 1;
      fi
    - >
      if (( $var > 250)); then
        echo "Your artist statement should only be 200 words!";
        exit 1;
      fi

# have you committed & pushed your thumbnail.png file
thumbnail:
  stage: test
  allow_failure: true
  tags:
    - comp1720
  script:
    - python /validate.py exists thumbnail.png

# check that you've filled out your references file
references:
  stage: test
  allow_failure: true
  tags:
    - comp1720
  script:
    - python /validate.py ref-check ./references.md 2

# this task copies the sketch files to the COMP1720 test webserver so they can
# be viewed on-campus
deploy:
  image: comp17202020/comp1720-2020-gitlab-ci:0.5.0
  stage: deploy
  tags:
    - comp1720
  only:
    - main
  script:
    - mkdir -p $DEST_DIR
    # copy assets folder, and all top-level .html and .js files
    - cp -r * $DEST_DIR
    - echo "your sketch should be visible shortly (on campus only) at the test URL"
    - echo $COMP1720_TEST_URL